site_name: MacLéinn Archive
site_url: https://macleinnarchive.com/

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.tracking

plugins:
  - search:
      lang: en
      separator: '[\s\-]+'

nav:
  - Home: index.md
  - Contact: contact.md
  - UL:
      - PSU: ul/PSU.md
      - ULSL: ul/ULSL.md
  - UG:
      - CML OnG: ug/CMLONG.md
