site_name: MacLeinn Archive
site_url: https://macleinnarchive.com/

theme:
  name: material
  features:
    - search.suggest
    - search.highlight

plugins:
  - search

nav:
  - Home: index.md
  - Contact: contact.md
